apiVersion: v1
kind: Pod
metadata:
  name: ip-display-pod
spec:
  containers:
  - name: ip-display-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do ifconfig > /www/index.html; sleep 10; done"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-content
      mountPath: /www
  volumes:
  - name: web-content
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ip-display-svc
spec:
  selector:
    app: ip-display-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
