apiVersion: v1     
kind: Pod                         
metadata:           
  name: webserver-validator-node
  labels:
    app.kubernetes.io/name: proxy 
spec:             
  containers:
  - name: webserver  
    image: nginx:latest 
    ports:               
    - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: ip-display-svc
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort